### ISSUE TITLE
Default config

### ISSUE THREAD

**Issue by maxvanceffer** [tgalopin/AudienceBundle#3]
I installed this bundle using documentation. 

And when i tried to use it in my controller, i had such error^ 

 PHP Fatal error:  Uncaught exception 'Doctrine\\ORM\\ORMException' with message 'Unknown Entity namespace alias 'TgaAudienceBundle'.'

Also please add to documentation to setup steps

```doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                     TgaAudienceBundle: ~
```

**Comment by tgalopin** [comment]
Hi @maxvanceffer,

Thanks for the reporting!

This bundle is not maintened anymore and was more an implementation of an idea I had a couple of years ago (I should write it on the README). I recommand you to use Google Analytics or another analytics tool as this bundle is very limited compared to these.

However, if you still want to create your own audience system, I would recommand you to not use this bundle and implements your versions of `Stats/Processor.php` and `Listener/KernelListener.php`.

If you need help or advices, I'd be pleased to give a hand :) .

**Comment by maxvanceffer** [comment]
Ah, sounds bad... Some times, for my projects i don't need such huge audience system such as google. Or i don't want to use google for this purpose.

**Comment by maxvanceffer** [comment]
Thx anyway
